steps:
  - name: maven:3.6.3-jdk-11
    args: ['clean package appengine:deploy']
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: ['beta app deploy ./backend/pom.xml --no-promote --project blindepoule']