runtime: nodejs20

# Leejjon: I first wanted to call this service "frontend", but having a default service seems to be required.
# Source: https://stackoverflow.com/questions/42360790/why-do-i-need-to-deploy-a-default-app-before-i-can-deploy-multiple-services-in/42361987#42361987
service: default
env: standard
instance_class: F1
default_expiration: "7d 0h"

# These handlers are not easy tbh. Documentation: https://cloud.google.com/appengine/docs/standard/python/config/appref#handlers_element
handlers:
  - url: /assets
    static_dir: dist/build/assets
  - url: /(.*\.(json|ico|js|png|txt|svg|jpg))$
    static_files: dist/build/\1
    upload: dist/build/.*\.(json|ico|js|png|txt|svg|jpg)$
  - url: '.*'
    script: auto
    secure: always
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

# [END app_yaml]
