### Get all competitions
GET {{footballdata-api-url}}/v2/competitions
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Get BundesLiga teams
GET {{footballdata-api-url}}/v2/competitions/2002/teams
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Get Ligue un teams
GET {{footballdata-api-url}}/v2/competitions/2015/teams
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Get Ligue un teams
GET {{footballdata-api-url}}/v2/competitions/2017/teams
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Eredivisie matches
GET {{footballdata-api-url}}/v4/competitions/2003/matches
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Premier league
GET {{footballdata-api-url}}/v2/competitions/2021/matches
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Premier league teams
GET {{footballdata-api-url}}/v2/competitions/2021/teams
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### La Liga teams
GET {{footballdata-api-url}}/v2/competitions/2014/teams
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### La Liga matches
GET {{footballdata-api-url}}/v2/competitions/2014/matches
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Serie A teams
GET {{footballdata-api-url}}/v2/competitions/2019/teams
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Serie A matches
GET {{footballdata-api-url}}/v2/competitions/2019/matches
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Primeira liga teams
GET {{footballdata-api-url}}/v2/competitions/2017/teams
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Primeira liga matches
GET {{footballdata-api-url}}/v2/competitions/2017/matches
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### Champions league matches
GET {{footballdata-api-url}}/v2/competitions/2001/teams
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### World cup 2022 matches
GET {{footballdata-api-url}}/v4/competitions/2000/matches
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### World cup 2022 teams
GET {{footballdata-api-url}}/v4/competitions/2000/teams
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}

### European cup 2018 matches
GET {{footballdata-api-url}}/v4/competitions/2018/matches
Accept: application/json
X-Auth-Token: {{footballdata-api-key}}
