# Update new matches
GET {{matches-api-url}}/api/v2/matches/update

### This separator is required in .http files

# Get upcoming matches
GET {{matches-api-url}}/api/v2/matches/upcoming?competition[]=2021&competition[]=2003
Accept: application/json


