runtime: java11
service: backend
instance_class: F2
entrypoint: 'java -p ./ -m blindpool.backend/net.leejjon.blindpool.server.Main'
handlers:
  - url: /.*
    script: true
    secure: always
    redirect_http_response_code: 301