runtime: java11
service: backend
instance_class: F2
entrypoint: 'java --illegal-access=permit -agentpath:/srv/cprof/profiler_java_agent.so=--logtostderr -cp * com.google.appengine.demo.jettymain.Main warfile.war'